<?php

/**
 * @file
 * Provides useful methods to work in an easier way with Drupal.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupal_toolkit_social_networks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.drupal_toolkit_social_networks':
      $output = '<h3>' . t('Drupal Toolkit Social Networks') . '</h3>';

      return $output;
  }
}
