id: book
label: Import books
migration_groups:
  - Book import
source:
  plugin: csv
  path: "public://migration_csv/book.csv"
  header_row_count: 1
  delimiter: ','
  keys:
    - title
  column_names:
    0:
      title: Título
    1:
      body: Cuerpo
process:
  type:
    plugin: default_value
    default_value: libro
  title: title
  field_titulo: title
  body: body
  langcode:
    plugin: default_value
    default_value: es
destination:
  plugin: entity:node