# Schema for the configuration files of the migrate default content module.

migrate_default_content.settings:
  type: config_object
  label: 'migrate_default_content settings'
  mapping:
    source_dir:
      type: string
      label: 'Files source directory'
