<?php
/**
 * @file
 * Make base fields such as 'title' available in "Manage Display".
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\node\Entity\NodeType;

/**
 * Implements hook_entity_base_field_info_alter().
 */
function manage_display_entity_base_field_info_alter(&$base_field_definitions, EntityTypeInterface $entity_type) {
  $info = manage_display_base_field_info($entity_type->id());
  foreach ($info as $field => $options) {
    $base_field_definitions[$field]
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('view', $options);
  }
}

/**
 * Return information about the base fields that can be managed.
 *
 * @param string $entity_type_id
 *   Entity type ID to return fields for.
 *
 * @return array
 *   Array keyed by field name with value equal to the default display options.
 */
function manage_display_base_field_info($entity_type_id) {
  $info['node']['title'] = [
    'label' => 'hidden',
    'type' => 'title',
    'weight' => -5,
  ];

  $info['user']['name'] = $info['node']['title'];
  $info['taxonomy_term']['name'] = $info['node']['title'];

  // @todo Alter hook
  // @todo Configure which are enabled.
  // @todo Static cache
  // @todo hook_uninstall to remove all changes made

  return isset($info[$entity_type_id]) ? $info[$entity_type_id] : [];
}

/**
 * Implements hook_theme().
 */
function manage_display_theme() {
  return [
    'submitted' => [
      'variables' => [
        'author_picture' => NULL,
        'metadata' => NULL,
        'date' => NULL,
        'author_name' => NULL,
        'author_attributes' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_entity_extra_field_info();
 */
function manage_display_entity_extra_field_info() {
  $extra = array();
  $description = t('Author and creation date.');

  foreach (NodeType::loadMultiple() as $bundle) {
    if ($bundle->displaySubmitted()) {
      $extra['node'][$bundle->id()]['display']['submitted'] = array(
        'label' => t('Submitted information'),
        'description' => $description,
        'weight' => -4,
        'visible' => TRUE,
      );
    }
  }

  return $extra;
}

/**
 * Implements hook_preprocess_node().
 */
function manage_display_preprocess_node(&$variables) {
  // Move 'submitted' variables into the child element to that they can be
  // positioned correctly relative to other fields.
  foreach (['author_picture', 'metadata', 'date', 'author_name', 'author_attributes'] as $key) {
    if (isset($variables[$key])) {
      $variables['content']['submitted']["#$key"] = $variables[$key];
      unset($variables[$key]);
    }
  }
  $variables['content']['submitted']['#theme'] = 'submitted';
}
