<?php

/**
 * @file
 * Contains csd_menu.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function csd_menu_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the csd_menu module.
    case 'help.page.csd_menu':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('CSD - Custom development') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function csd_menu_theme($existing, $type, $theme, $path) {
  return [
    'csd_menu_main' => [
      'variables' => [
        'menu_root' => '',
        'items' => '',
      ],
      'template' => 'csd-menu-main',
    ],
  ];
}

function csd_menu_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->bundle() == 'node') {
    $title = $entity->label();
    $id = $entity->id();
    if ($entity->hasField('field_category')) {
      $categories = $entity->get('field_category')->getValue();
      if (!empty($categories) & is_array($categories)) {
        foreach ($categories as $category) {
          if (isset($category['target_id'])) {
            $tid = $category['target_id'];
            $x='a';
            /*
            $menuu = $entity->get('menu');
            $menu_value = $entity->get('menu')->value;
            $url = 'node/' . $entity->id();
            */
            if ($tid) {
              $menu_name = 'main';
              $taxonomy_name = 'category';
              //$menu_handler = \Drupal::service('plugin.manager.menu.link');
              //$parent = 'main:taxonomy_menu.menu_link:taxonomy_menu.menu_link.category.4';
              $parent = $menu_name. ':taxonomy_menu.menu_link:taxonomy_menu.menu_link.'. $taxonomy_name . '.' . $tid;
              $menu_item = \Drupal\menu_link_content\Entity\MenuLinkContent::create([
                'title' => $title,
                'link' => ['uri' => 'internal:/node/' . $id],
                'menu_name' => $menu_name,
                'parent' => $parent,
                'expanded' => TRUE,
              ]);

              $menu_item->save();
            }
          }
        }
      }
    }
    else {
      $x='aa';
    }
  }
}